version: "3"
services:
  hub:
    image: selenium/hub:3.141
  chrome:
    image: selenium/node-chrome:3.141
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.141
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  search-module:
    image: jileb/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=firefox
      - MODULE=search-module.xml
    volumes:
    - .\output\search-module:/usr/share/selenium-docker/test-output
  book-flight-module:
    image: jileb/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=chrome
      - MODULE=book-flight.xml
    volumes:
      - .\output\book-flight-module:/usr/share/selenium-docker/test-output
